# Generated by Django 5.2.4 on 2025-07-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('annual_income', models.FloatField()),
                ('spending_score', models.FloatField()),
            ],
        ),
    ]
